// Properties
const USER_PROFILE_PROPERTY = 'userProfile';
const DIALOG_STATE_PROPERTY = 'dialogState';
const WHO_ARE_YOU = 'WHO_ARE_YOU';
const CANDIDATE_SUBMIT_SUCCESS = 'CANDIDATE_SUBMIT_SUCCESS';
const GREET_CANDIDATE = 'GREET_CANDIDATE';

module.exports = {
    USER_PROFILE_PROPERTY,
    DIALOG_STATE_PROPERTY,
    WHO_ARE_YOU,
    CANDIDATE_SUBMIT_SUCCESS,
    GREET_CANDIDATE
}
;
