// Properties
const USER_PROFILE_PROPERTY = 'userProfile';
const DIALOG_STATE_PROPERTY = 'dialogState';
const NAME_PROMPT = 'NAME_PROMPT';
const WHO_ARE_YOU = 'WHO_ARE_YOU';
const CANDIDATE_SUBMIT_SUCCESS = 'CANDIDATE_SUBMIT_SUCCESS';

module.exports = {
    USER_PROFILE_PROPERTY,
    DIALOG_STATE_PROPERTY,
    NAME_PROMPT,
    WHO_ARE_YOU,
    CANDIDATE_SUBMIT_SUCCESS
}
;
